import os
import datetime

# --- CẤU HÌNH ---
EXCLUDED_DIRS = {'.git', '.github', '.idea', '__pycache__'}
EXCLUDED_FILES = {'index.html', 'gen_index.py', 'chay-cai-nay.bat', '.gitignore', '.DS_Store', 'README.md'}

def get_size_format(b, factor=1024, suffix="B"):
    for unit in ["", "K", "M", "G", "T", "P"]:
        if b < factor: return f"{b:.2f} {unit}{suffix}"
        b /= factor
    return f"{b:.2f} Y{suffix}"

def get_icon(name, is_dir=False):
    if is_dir: return "📁"
    ext = name.split('.')[-1].lower()
    if ext in ['zip', 'rar', '7z']: return "📦"
    if ext in ['apk']: return "🤖"
    if ext in ['jpg', 'png']: return "🖼️"
    return "📄"

def generate_html_for_dir(path):
    try:
        # Lấy danh sách file và thư mục
        items = os.listdir(path)
        dirs = []
        files = []

        for item in items:
            full_path = os.path.join(path, item)
            if item in EXCLUDED_FILES or item in EXCLUDED_DIRS: continue
            
            if os.path.isdir(full_path):
                dirs.append(item)
            else:
                files.append(item)
        
        dirs.sort()
        files.sort()

        # Nội dung HTML
        html = f"""
        <!DOCTYPE html>
        <html lang="vi">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Index of {path}</title>
            <style>
                body {{ font-family: sans-serif; background: #f4f4f4; padding: 20px; }}
                .container {{ max-width: 900px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }}
                h2 {{ border-bottom: 1px solid #eee; padding-bottom: 10px; }}
                table {{ width: 100%; border-collapse: collapse; }}
                td, th {{ padding: 10px; border-bottom: 1px solid #eee; text-align: left; }}
                a {{ text-decoration: none; color: #0366d6; display: block; }}
                a:hover {{ text-decoration: underline; }}
                .icon {{ margin-right: 8px; }}
                .size {{ font-family: monospace; color: #666; }}
            </style>
        </head>
        <body>
        <div class="container">
            <h2>Index of /{path.replace(os.sep, '/')}</h2>
            <table>
                <thead><tr><th>Name</th><th width="20%">Size</th></tr></thead>
                <tbody>
        """

        # Link quay lại (nếu không phải thư mục gốc)
        if path != '.':
            html += '<tr><td><a href="../"><span class="icon">🔙</span> [Parent Directory]</a></td><td>-</td></tr>'

        # Liệt kê Thư mục trước
        for d in dirs:
            html += f'<tr><td><a href="{d}/"><span class="icon">📁</span> <b>{d}</b></a></td><td>-</td></tr>'

        # Liệt kê File sau
        for f in files:
            file_path = os.path.join(path, f)
            size = get_size_format(os.path.getsize(file_path))
            html += f'<tr><td><a href="{f}"><span class="icon">{get_icon(f)}</span> {f}</a></td><td class="size">{size}</td></tr>'

        html += """
                </tbody>
            </table>
            <div style="margin-top:20px;text-align:center;color:#999;font-size:12px">Auto-generated by Python</div>
        </div>
        </body>
        </html>
        """

        # Ghi file index.html vào đúng thư mục đó
        with open(os.path.join(path, "index.html"), "w", encoding="utf-8") as f:
            f.write(html)
            
    except Exception as e:
        print(f"Lỗi tại {path}: {e}")

# --- CHẠY QUÉT ---
print("dang quet thu muc...")
for root, dirs, files in os.walk('.', topdown=True):
    # Loại bỏ các thư mục hệ thống
    dirs[:] = [d for d in dirs if d not in EXCLUDED_DIRS]
    
    generate_html_for_dir(root)

print("✅ ĐÃ XONG! Đã tạo index.html cho tất cả thư mục con.")